import type { Event } from "./types";

export const EVENTS: Event[] = [
  {
    id: "nypl-001",
    title: "Intro to Digital Photography",
    description:
      "Learn the fundamentals of digital photography in this hands-on workshop. Topics include composition, lighting, aperture, and shutter speed. Bring your own camera or smartphone. All skill levels welcome.",
    source: "NYPL",
    venue: {
      name: "Mid-Manhattan Library",
      address: "455 5th Ave",
      borough: "Manhattan",
      zip: "10016",
      lat: 40.7529,
      lng: -73.9825,
    },
    date: "2026-06-13",
    startTime: "10:00",
    endTime: "12:00",
    cost: "Free",
    category: "photography",
    registrationUrl: "https://www.nypl.org/events",
    contactEmail: "programs@nypl.org",
    isCanceled: false,
    sourceEventId: "nypl-evt-4421",
    interestedCount: 34,
  },
  {
    id: "nypl-002",
    title: "Poetry Open Mic: Harlem Voices",
    description:
      "An open mic night celebrating the rich poetic tradition of Harlem. Read your own work or come to listen. All forms and styles welcome — spoken word, haiku, free verse. Sign-up starts at 6pm.",
    source: "NYPL",
    venue: {
      name: "Countee Cullen Library",
      address: "104 W 136th St",
      borough: "Manhattan",
      zip: "10030",
      lat: 40.8155,
      lng: -73.9403,
    },
    date: "2026-06-14",
    startTime: "18:00",
    endTime: "20:00",
    cost: "Free",
    category: "poetry",
    registrationUrl: "https://www.nypl.org/events",
    contactPhone: "212-491-2070",
    isCanceled: false,
    sourceEventId: "nypl-evt-4422",
    interestedCount: 51,
  },
  {
    id: "nypl-003",
    title: "Excel for Job Seekers",
    description:
      "Master the spreadsheet skills employers want most. This workshop covers formulas, pivot tables, data visualization, and formatting. Taught by a certified Microsoft Office instructor. Laptops available for use.",
    source: "NYPL",
    venue: {
      name: "Seward Park Library",
      address: "192 E Broadway",
      borough: "Manhattan",
      zip: "10002",
      lat: 40.7135,
      lng: -73.9887,
    },
    date: "2026-06-16",
    startTime: "14:00",
    endTime: "16:00",
    cost: "Free",
    category: "careers",
    registrationUrl: "https://www.nypl.org/events",
    contactEmail: "programs@nypl.org",
    isCanceled: false,
    sourceEventId: "nypl-evt-4423",
    interestedCount: 72,
  },
  {
    id: "nypl-004",
    title: "Summer Reading Kickoff: Crafts & Storytime",
    description:
      "Launch summer reading with crafts, storytime, and activities for kids ages 4–10. Make a bookmark, hear stories about faraway places, and pick up your summer reading log. Light snacks provided.",
    source: "NYPL",
    venue: {
      name: "Hamilton Fish Park Library",
      address: "415 E Houston St",
      borough: "Manhattan",
      zip: "10002",
      lat: 40.7231,
      lng: -73.9755,
    },
    date: "2026-06-14",
    startTime: "11:00",
    endTime: "12:30",
    cost: "Free",
    category: "kids-teens",
    registrationUrl: "https://www.nypl.org/events",
    contactPhone: "212-673-2290",
    isCanceled: false,
    sourceEventId: "nypl-evt-4424",
    interestedCount: 28,
  },
  {
    id: "nypl-005",
    title: "Beginner Python Programming",
    description:
      "No coding experience needed. This three-hour workshop introduces Python fundamentals: variables, loops, functions, and file I/O. You will leave with a working script and a list of next steps. Computers provided.",
    source: "NYPL",
    venue: {
      name: "Fort Washington Library",
      address: "535 W 179th St",
      borough: "Manhattan",
      zip: "10033",
      lat: 40.8498,
      lng: -73.9352,
    },
    date: "2026-06-17",
    startTime: "18:30",
    endTime: "21:30",
    cost: "Free",
    category: "tech-digital-skills",
    registrationUrl: "https://www.nypl.org/events",
    contactEmail: "programs@nypl.org",
    isCanceled: false,
    sourceEventId: "nypl-evt-4425",
    interestedCount: 89,
  },
  {
    id: "nypl-006",
    title: "Author Talk: Gloria Okafor on Migration and Memory",
    description:
      "Debut novelist Gloria Okafor reads from and discusses her novel 'The Distance Between Rivers,' a multigenerational story of a Nigerian family in the Bronx. Q&A and book signing to follow.",
    source: "NYPL",
    venue: {
      name: "Parkchester Library",
      address: "1985 Westchester Ave",
      borough: "Bronx",
      zip: "10462",
      lat: 40.8337,
      lng: -73.8623,
    },
    date: "2026-06-18",
    startTime: "18:00",
    endTime: "19:30",
    cost: "Free",
    category: "literature",
    registrationUrl: "https://www.nypl.org/events",
    contactEmail: "parkchester@nypl.org",
    isCanceled: false,
    sourceEventId: "nypl-evt-4426",
    interestedCount: 45,
  },
  {
    id: "nypl-007",
    title: "SAT Prep: Math Strategies",
    description:
      "Taught by a certified test prep instructor, this 90-minute session covers algebra, data analysis, and advanced math sections. Workbooks included. Geared toward 10th and 11th graders taking the SAT this fall.",
    source: "NYPL",
    venue: {
      name: "Mott Haven Library",
      address: "321 E 140th St",
      borough: "Bronx",
      zip: "10454",
      lat: 40.8143,
      lng: -73.9248,
    },
    date: "2026-06-21",
    startTime: "13:00",
    endTime: "14:30",
    cost: "Free",
    category: "test-prep-education",
    registrationUrl: "https://www.nypl.org/events",
    contactEmail: "programs@nypl.org",
    isCanceled: false,
    sourceEventId: "nypl-evt-4427",
    interestedCount: 63,
  },
  {
    id: "nypl-008",
    title: "Watercolor for Beginners",
    description:
      "Explore watercolor painting in a relaxed, drop-in session. An artist guide will demonstrate core techniques — wet-on-wet, dry brush, gradients — and you will complete a small piece to take home. All supplies provided.",
    source: "NYPL",
    venue: {
      name: "Washington Heights Library",
      address: "1000 St Nicholas Ave",
      borough: "Manhattan",
      zip: "10032",
      lat: 40.8397,
      lng: -73.9399,
    },
    date: "2026-06-19",
    startTime: "16:00",
    endTime: "18:00",
    cost: "Free",
    category: "arts-crafts",
    registrationUrl: "https://www.nypl.org/events",
    contactPhone: "212-923-6054",
    isCanceled: false,
    sourceEventId: "nypl-evt-4428",
    interestedCount: 41,
  },
  {
    id: "bpl-001",
    title: "Resume Writing Workshop",
    description:
      "A career counselor will walk through how to tailor your resume for today's job market. Bring a printed or digital draft for individualized feedback. ATS optimization, formatting, and summary statement tips covered.",
    source: "BPL",
    venue: {
      name: "Brooklyn Central Library",
      address: "10 Grand Army Plaza",
      borough: "Brooklyn",
      zip: "11238",
      lat: 40.6727,
      lng: -73.968,
    },
    date: "2026-06-13",
    startTime: "12:00",
    endTime: "14:00",
    cost: "Free",
    category: "careers",
    registrationUrl: "https://www.bklynlibrary.org/calendar",
    contactEmail: "programs@bklynlibrary.org",
    isCanceled: false,
    sourceEventId: "bpl-evt-8831",
    interestedCount: 77,
  },
  {
    id: "bpl-002",
    title: "Teen Zine Workshop",
    description:
      "Create your own zine — a hand-made mini-magazine — in this afternoon workshop for teens ages 13–18. Bring stories, drawings, comics, or poetry. Materials provided. Zines will be displayed in the library for two weeks.",
    source: "BPL",
    venue: {
      name: "Flatbush Library",
      address: "22 Linden Blvd",
      borough: "Brooklyn",
      zip: "11226",
      lat: 40.6471,
      lng: -73.959,
    },
    date: "2026-06-15",
    startTime: "14:00",
    endTime: "16:30",
    cost: "Free",
    category: "kids-teens",
    registrationUrl: "https://www.bklynlibrary.org/calendar",
    contactPhone: "718-856-0813",
    isCanceled: false,
    sourceEventId: "bpl-evt-8832",
    interestedCount: 22,
  },
  {
    id: "bpl-003",
    title: "Brooklyn Reads: Toni Morrison Book Circle",
    description:
      "A monthly discussion of Morrison's work. This month: 'Jazz.' New readers and longtime Morrison devotees are welcome. Light refreshments. Discussion guide available at the reference desk.",
    source: "BPL",
    venue: {
      name: "Williamsburg Library",
      address: "240 Division Ave",
      borough: "Brooklyn",
      zip: "11211",
      lat: 40.7071,
      lng: -73.9497,
    },
    date: "2026-06-17",
    startTime: "18:30",
    endTime: "20:00",
    cost: "Free",
    category: "literature",
    registrationUrl: "https://www.bklynlibrary.org/calendar",
    contactEmail: "programs@bklynlibrary.org",
    isCanceled: false,
    sourceEventId: "bpl-evt-8833",
    interestedCount: 38,
  },
  {
    id: "bpl-004",
    title: "Smartphone Photography: Getting the Most from Your Phone",
    description:
      "A professional photographer shows you how to use your phone's camera to its full potential. Topics include portrait mode, night photography, editing apps, and how to share your work. Bring your fully-charged phone.",
    source: "BPL",
    venue: {
      name: "Bay Ridge Library",
      address: "9223 Ridge Blvd",
      borough: "Brooklyn",
      zip: "11209",
      lat: 40.6209,
      lng: -74.0269,
    },
    date: "2026-06-14",
    startTime: "11:00",
    endTime: "13:00",
    cost: "Free",
    category: "photography",
    registrationUrl: "https://www.bklynlibrary.org/calendar",
    contactPhone: "718-748-5709",
    isCanceled: false,
    sourceEventId: "bpl-evt-8834",
    interestedCount: 55,
  },
  {
    id: "bpl-005",
    title: "Intro to ChatGPT & AI Tools for Everyday Life",
    description:
      "Curious about AI but not sure where to start? This workshop demystifies AI chatbots, explains what they can and can't do, and walks through practical uses: writing emails, researching, summarizing documents. No tech background required.",
    source: "BPL",
    venue: {
      name: "Crown Heights Library",
      address: "560 New York Ave",
      borough: "Brooklyn",
      zip: "11225",
      lat: 40.6654,
      lng: -73.947,
    },
    date: "2026-06-18",
    startTime: "10:00",
    endTime: "12:00",
    cost: "Free",
    category: "tech-digital-skills",
    registrationUrl: "https://www.bklynlibrary.org/calendar",
    contactEmail: "programs@bklynlibrary.org",
    isCanceled: false,
    sourceEventId: "bpl-evt-8835",
    interestedCount: 94,
  },
  {
    id: "bpl-006",
    title: "Sunset Park Evening Yoga",
    description:
      "A gentle, beginner-friendly yoga class held on the library's outdoor plaza (weather permitting; moves inside if needed). All levels and all bodies welcome. Bring a mat or towel. Instructor: Mia Torres.",
    source: "BPL",
    venue: {
      name: "Sunset Park Library",
      address: "4201 4th Ave",
      borough: "Brooklyn",
      zip: "11232",
      lat: 40.6498,
      lng: -74.0089,
    },
    date: "2026-06-16",
    startTime: "18:00",
    endTime: "19:00",
    cost: "Free",
    category: "fitness",
    registrationUrl: "https://www.bklynlibrary.org/calendar",
    contactPhone: "718-567-2806",
    isCanceled: false,
    sourceEventId: "bpl-evt-8836",
    interestedCount: 31,
  },
  {
    id: "bpl-007",
    title: "Crochet Circle: Summer Stitch-Along",
    description:
      "Join our weekly drop-in crochet group. Beginners can learn the chain and single crochet; veterans bring your current WIP. Yarn and hooks available to borrow. All ages welcome.",
    source: "BPL",
    venue: {
      name: "Greenpoint Library",
      address: "107 Norman Ave",
      borough: "Brooklyn",
      zip: "11222",
      lat: 40.7246,
      lng: -73.9487,
    },
    date: "2026-06-20",
    startTime: "14:00",
    endTime: "16:00",
    cost: "Free",
    category: "arts-crafts",
    registrationUrl: "https://www.bklynlibrary.org/calendar",
    contactEmail: "programs@bklynlibrary.org",
    isCanceled: false,
    sourceEventId: "bpl-evt-8837",
    interestedCount: 19,
  },
  {
    id: "bpl-008",
    title: "Poetry Slam & Open Mic: Crown Heights Edition",
    description:
      "Monthly poetry slam hosted by the Crown Heights Poetry Collective. Three-minute open mic slots followed by a featured reader. Sign up in advance or at the door. Ages 16 and up.",
    source: "BPL",
    venue: {
      name: "Crown Heights Library",
      address: "560 New York Ave",
      borough: "Brooklyn",
      zip: "11225",
      lat: 40.6654,
      lng: -73.947,
    },
    date: "2026-06-22",
    startTime: "19:00",
    endTime: "21:00",
    cost: "Free",
    category: "poetry",
    registrationUrl: "https://www.bklynlibrary.org/calendar",
    contactPhone: "718-773-5533",
    isCanceled: false,
    sourceEventId: "bpl-evt-8838",
    interestedCount: 46,
  },
  {
    id: "qpl-001",
    title: "English Conversation Circle",
    description:
      "Practice conversational English in a welcoming, supportive environment. A trained facilitator leads structured conversation practice around everyday topics. Open to adults at all English proficiency levels. Sessions held in English only.",
    source: "QPL",
    venue: {
      name: "Flushing Library",
      address: "41-17 Main St",
      borough: "Queens",
      zip: "11355",
      lat: 40.7571,
      lng: -73.8309,
    },
    date: "2026-06-13",
    startTime: "10:00",
    endTime: "11:30",
    cost: "Free",
    category: "test-prep-education",
    registrationUrl: "https://queenslibrary.org/calendar",
    contactEmail: "programs@queenslibrary.org",
    isCanceled: false,
    sourceEventId: "qpl-evt-2201",
    interestedCount: 57,
  },
  {
    id: "qpl-002",
    title: "GED Prep: Reading and Writing",
    description:
      "Free GED preparation class covering extended response writing, reading comprehension, and vocabulary for the Reasoning Through Language Arts section. Textbooks provided. Consistent attendance strongly encouraged.",
    source: "QPL",
    venue: {
      name: "Jamaica Library",
      address: "89-11 Merrick Blvd",
      borough: "Queens",
      zip: "11432",
      lat: 40.7041,
      lng: -73.7975,
    },
    date: "2026-06-15",
    startTime: "10:00",
    endTime: "12:00",
    cost: "Free",
    category: "test-prep-education",
    registrationUrl: "https://queenslibrary.org/calendar",
    contactPhone: "718-990-0700",
    isCanceled: false,
    sourceEventId: "qpl-evt-2202",
    interestedCount: 66,
  },
  {
    id: "qpl-003",
    title: "Flamenco Roots: Music & Dance History",
    description:
      "A lecture-demonstration exploring the history and cultural roots of flamenco music and dance. Performer and historian Ana Reyes presents live examples and discusses the Romani, Moorish, and Spanish influences that shaped this art form.",
    source: "QPL",
    venue: {
      name: "Jackson Heights Library",
      address: "35-51 81st St",
      borough: "Queens",
      zip: "11372",
      lat: 40.7476,
      lng: -73.8836,
    },
    date: "2026-06-19",
    startTime: "18:00",
    endTime: "19:30",
    cost: "Free",
    category: "music",
    registrationUrl: "https://queenslibrary.org/calendar",
    contactEmail: "programs@queenslibrary.org",
    isCanceled: false,
    sourceEventId: "qpl-evt-2203",
    interestedCount: 39,
  },
  {
    id: "qpl-004",
    title: "Intro to LinkedIn for Career Changers",
    description:
      "A practical workshop for adults changing careers or returning to the workforce. Learn how to build a compelling LinkedIn profile, grow your network, and use the platform for job research. Computers and library WiFi available.",
    source: "QPL",
    venue: {
      name: "Astoria Library",
      address: "14-01 Astoria Blvd",
      borough: "Queens",
      zip: "11102",
      lat: 40.7717,
      lng: -73.9297,
    },
    date: "2026-06-17",
    startTime: "17:30",
    endTime: "19:00",
    cost: "Free",
    category: "careers",
    registrationUrl: "https://queenslibrary.org/calendar",
    contactPhone: "718-278-2220",
    isCanceled: false,
    sourceEventId: "qpl-evt-2204",
    interestedCount: 83,
  },
  {
    id: "qpl-005",
    title: "Kids' Science Lab: States of Matter",
    description:
      "Children ages 6–12 explore solids, liquids, and gases through hands-on experiments: make slime, observe dry ice sublimation, and build a model of the water cycle. Presented by a Queens Science Education volunteer.",
    source: "QPL",
    venue: {
      name: "Long Island City Library",
      address: "37-44 21st St",
      borough: "Queens",
      zip: "11101",
      lat: 40.7498,
      lng: -73.9355,
    },
    date: "2026-06-14",
    startTime: "11:00",
    endTime: "12:30",
    cost: "Free",
    category: "kids-teens",
    registrationUrl: "https://queenslibrary.org/calendar",
    contactEmail: "programs@queenslibrary.org",
    isCanceled: false,
    sourceEventId: "qpl-evt-2205",
    interestedCount: 29,
  },
  {
    id: "qpl-006",
    title: "Street Photography: The City as Canvas",
    description:
      "Photographer Marcus Chen leads a two-hour workshop on documentary-style street photography. Covers ethics, technique, and light in urban settings. Followed by a 45-minute critique of participant images.",
    source: "QPL",
    venue: {
      name: "Flushing Library",
      address: "41-17 Main St",
      borough: "Queens",
      zip: "11355",
      lat: 40.7571,
      lng: -73.8309,
    },
    date: "2026-06-20",
    startTime: "14:00",
    endTime: "17:00",
    cost: "Free",
    category: "photography",
    registrationUrl: "https://queenslibrary.org/calendar",
    contactPhone: "718-661-1200",
    isCanceled: false,
    sourceEventId: "qpl-evt-2206",
    interestedCount: 48,
  },
  {
    id: "qpl-007",
    title: "Morning Tai Chi in the Garden",
    description:
      "Start your day with a gentle Tai Chi session in the library's garden courtyard. Instructor David Park leads a 45-minute form accessible to all ages and fitness levels. No equipment needed. Arrive 5 minutes early.",
    source: "QPL",
    venue: {
      name: "Hollis Library",
      address: "202-05 Hillside Ave",
      borough: "Queens",
      zip: "11423",
      lat: 40.7123,
      lng: -73.7654,
    },
    date: "2026-06-21",
    startTime: "09:00",
    endTime: "10:00",
    cost: "Free",
    category: "fitness",
    registrationUrl: "https://queenslibrary.org/calendar",
    contactEmail: "programs@queenslibrary.org",
    isCanceled: false,
    sourceEventId: "qpl-evt-2207",
    interestedCount: 25,
  },
  {
    id: "qpl-008",
    title: "Spanish-Language Poetry Afternoon",
    description:
      "Una tarde de poesía en español abierta a todos. Lecturas de poetas locales y clásicos latinoamericanos, seguido de un micrófono abierto. / An afternoon of Spanish-language poetry open to all, featuring local poets and Latin American classics.",
    source: "QPL",
    venue: {
      name: "Jackson Heights Library",
      address: "35-51 81st St",
      borough: "Queens",
      zip: "11372",
      lat: 40.7476,
      lng: -73.8836,
    },
    date: "2026-06-22",
    startTime: "15:00",
    endTime: "17:00",
    cost: "Free",
    category: "poetry",
    registrationUrl: "https://queenslibrary.org/calendar",
    contactPhone: "718-899-2500",
    isCanceled: false,
    sourceEventId: "qpl-evt-2208",
    interestedCount: 34,
  },
  {
    id: "bpl-009",
    title: "Music Production Basics: Garageband & Logic",
    description:
      "Learn to record, arrange, and mix your own music using free and affordable software. A music producer walks through beat-making, vocal layering, and EQ fundamentals. Headphones and Mac laptops provided.",
    source: "BPL",
    venue: {
      name: "Brooklyn Central Library",
      address: "10 Grand Army Plaza",
      borough: "Brooklyn",
      zip: "11238",
      lat: 40.6727,
      lng: -73.968,
    },
    date: "2026-06-23",
    startTime: "17:00",
    endTime: "19:30",
    cost: "Free",
    category: "music",
    registrationUrl: "https://www.bklynlibrary.org/calendar",
    contactEmail: "programs@bklynlibrary.org",
    isCanceled: false,
    sourceEventId: "bpl-evt-8839",
    interestedCount: 71,
  },
  {
    id: "nypl-009",
    title: "Screen Printing: Design Your Own Tote",
    description:
      "Learn the basics of screen printing and go home with a custom-printed tote bag. Artist instructor Jasmine Reid guides participants through ink mixing, squeegee technique, and clean-up. Designs prepared in advance; samples provided.",
    source: "NYPL",
    venue: {
      name: "Schomburg Center",
      address: "515 Malcolm X Blvd",
      borough: "Manhattan",
      zip: "10037",
      lat: 40.8139,
      lng: -73.9414,
    },
    date: "2026-06-24",
    startTime: "17:00",
    endTime: "19:00",
    cost: "Free",
    category: "arts-crafts",
    registrationUrl: "https://www.nypl.org/events",
    contactPhone: "212-491-2200",
    isCanceled: false,
    sourceEventId: "nypl-evt-4429",
    interestedCount: 58,
  },
  {
    id: "nypl-010",
    title: "Reading Circle: Contemporary Fiction by Women of Color",
    description:
      "A curated reading group meeting monthly to discuss contemporary fiction. This month we discuss Yaa Gyasi's Homegoing. New members welcome — no need to have read in advance, just come curious.",
    source: "NYPL",
    venue: {
      name: "Seward Park Library",
      address: "192 E Broadway",
      borough: "Manhattan",
      zip: "10002",
      lat: 40.7135,
      lng: -73.9887,
    },
    date: "2026-06-25",
    startTime: "18:00",
    endTime: "20:00",
    cost: "Free",
    category: "literature",
    registrationUrl: "https://www.nypl.org/events",
    contactEmail: "programs@nypl.org",
    isCanceled: false,
    sourceEventId: "nypl-evt-4430",
    interestedCount: 43,
  },
  {
    id: "bpl-010",
    title: "Financial Literacy: Budgeting on a Variable Income",
    description:
      "Designed for freelancers, gig workers, and anyone with inconsistent paychecks. A certified financial planner covers budgeting methods, emergency fund strategies, and quarterly tax basics. Free workbook included.",
    source: "BPL",
    venue: {
      name: "Pacific Library",
      address: "25 Fourth Ave",
      borough: "Brooklyn",
      zip: "11217",
      lat: 40.6827,
      lng: -73.9811,
    },
    date: "2026-06-26",
    startTime: "18:30",
    endTime: "20:00",
    cost: "Free",
    category: "careers",
    registrationUrl: "https://www.bklynlibrary.org/calendar",
    contactPhone: "718-935-0203",
    isCanceled: false,
    sourceEventId: "bpl-evt-8840",
    interestedCount: 88,
  },
];

export function getEventById(id: string): Event | undefined {
  return EVENTS.find((e) => e.id === id);
}

export function getRelatedEvents(event: Event, limit = 3): Event[] {
  return EVENTS.filter(
    (e) => e.id !== event.id && (e.category === event.category || e.venue.borough === event.venue.borough)
  ).slice(0, limit);
}
